/**
 * Application limits and constraints.
 */
export const LIMITS = {
  MAX_MESSAGES_PER_CONVERSATION: 50,
  MAX_MESSAGE_LENGTH: 4096,
  MAX_REPLIES_PER_REQUEST: 5,
  DEFAULT_REPLIES_PER_REQUEST: 3,
  MAX_REPLY_LENGTH: 500,
  MIN_PASSWORD_LENGTH: 8,
  MAX_USERNAME_LENGTH: 64,
  DEBOUNCE_MS: 500,
  CONVERSATION_POLL_INTERVAL_MS: 2000,
  TOKEN_REFRESH_BUFFER_MS: 60_000, // Refresh token 1 min before expiry
} as const;
